force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <label>Notification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/BelongsTo__c.field-meta.xml
<CustomField>
    <fullName>BelongsTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BelongsTo</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Notification_Status__c.field-meta.xml
<CustomField>
    <fullName>Notification_Status__c</fullName>
    <label>Notification Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification__c/fields/User_Status__c.field-meta.xml
<CustomField>
    <fullName>User_Status__c</fullName>
    <label>User Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NotificationController.cls
public class NotificationController {
    
    public List<wrapNotification> wrapNotificationList {get; set;}
    public id currentUserId;
    
    public NotificationController(){
        currentUserId = UserInfo.getUserId();
    }
        
    public List<wrapNotification> getCurrentUserNotifications(){
        if(wrapNotificationList == null){
            wrapNotificationList = new List<wrapNotification>();
            for(Notification__c n : [Select id,Name,Notification_Status__c, User_Status__c From Notification__c
                Where BelongsTo__c =: currentUserId]){
                wrapNotification w = new wrapNotification(n);
                wrapNotificationList.add(w);
                System.debug(w);
            }
        }
        
        return wrapNotificationList;
    }
    
    public class wrapNotification {
        Notification__c notification;
        String title {get; set;}
        String titleLabel {get; set;}
        String dropableBody {get; set;}

        public wrapNotification(Notification__c n){
            notification = n;
            title = notification.id;
            titleLabel = notification.Name;
            dropableBody = 'Notification Status: ' + notification.Notification_Status__c + 
            ' / ' + 'User Status: ' + notification.User_Status__c;
        }
    }
}