force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <label>Notification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/DropableBody__c.field-meta.xml
<CustomField>
    <fullName>DropableBody__c</fullName>
    <label>DropableBody</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/IsDeletable__c.field-meta.xml
<CustomField>
    <fullName>IsDeletable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsDeletable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/titleLabel__c.field-meta.xml
<CustomField>
    <fullName>titleLabel__c</fullName>
    <label>titleLabel</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/THOR_ObjectCardMapper.cls
public with sharing class THOR_ObjectCardMapper{
	public THOR_ObjectCardMapper(){
	}

	public static List<THOR_ObjectCardDto> MapFromNotifications(List<Notification__c> notifications){
		List<THOR_ObjectCardDto> res = new List<THOR_ObjectCardDto>();
		for (Notification__c notification : notifications){
			res.add(new THOR_ObjectCardDto(notification.title__c, notification.titleLabel__c, notification.dropableBody__c, notification.isDeletable__c, true));
		}
		return res;
	}
}